### ISSUE TITLE
student search for coordinator view

### ISSUE THREAD

**Issue by chirangaw186** [DanushkaDissanayaka/Fit-Future-Careers#127]
api eken search karala ewanna

**Comment by DanushkaDissanayaka** [comment]
Sorting has done. it's better to do the search in front end using npm packge

**Comment by dulangaheshan** [comment]
feature implemented in frontend need to apply styles @Janitha133 
![image](https://user-images.githubusercontent.com/33221629/102486406-fda64c80-408e-11eb-9b06-443be732ccc4.png)

**Comment by Janitha133** [comment]
got it

**Comment by Janitha133** [comment]
done
